# Generated by Django 4.0.4 on 2022-05-31 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_nombre', models.CharField(max_length=30)),
                ('cli_pat_apellido', models.CharField(max_length=40)),
                ('cli_mat_apellido', models.CharField(max_length=40)),
                ('cli_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nombre', models.CharField(max_length=50)),
                ('prod_precio', models.IntegerField()),
                ('prod_descripcion', models.TextField()),
                ('prod_stock', models.IntegerField()),
                #('prod_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.venta')),
            ],
        ),
    ]
