# Generated by Django 4.0.4 on 2022-05-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
